# Generated by Django 4.0.3 on 2022-04-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_Main_Img',
            field=models.ImageField(default='NULL', upload_to='images/'),
            preserve_default=False,
        ),
    ]
