# Generated by Django 4.0.3 on 2022-04-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_profile_profile_main_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
