# Generated by Django 4.0.3 on 2022-04-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_profile_uname_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='uname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='ids',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
