# Generated by Django 4.0.3 on 2022-04-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_rename_user_profile_id2_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
